import "./globals.css";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import React from "react";
import BasicLayout from "@/layouts/BasicLayout";
/*
//国际化
const inter = Inter({ subsets: ["latin"] });

//标题描述
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body>
        <AntdRegistry>
            <BasicLayout>
                {children}
            </BasicLayout>
        </AntdRegistry>
      </body>
    </html>
  );
}
