"use client";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import React, { useCallback, useEffect } from "react";
import BasicLayout from "@/layouts/BasicLayout";
import store, {AppDispatch, RootState} from "@/stores";
import {Provider, useDispatch} from "react-redux";
import {getLoginUserUsingGet} from "@/api/userController";
import {setLoginUser} from "@/stores/loginUser";
/*
//国际化
const inter = Inter({ subsets: ["latin"] });

//标题描述
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

//全局初始化逻辑
const InitLayout: React.FC<
  Readonly<{
    children?: React.ReactNode;
  }>
> = ({ children }) => {
  const dispatch = useDispatch<AppDispatch>();
  //初始化逻辑
  const doInitLoginUser = useCallback(async () => {
    const res = await getLoginUserUsingGet();
    if (res.data) {
      //更新全局用户状态
    }else {
      //报错
      setTimeout(()=>{
        const testUser = {userName:"张三",id: 1,}
        dispatch(setLoginUser(testUser));
      },3000)
    }
  }, []);
  //只调用一次
  useEffect(() => {
    doInitLoginUser();
  }, []);
  return children;
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body>
        <AntdRegistry>
          <Provider store={store}>
            <InitLayout>
              <BasicLayout>{children}</BasicLayout>
            </InitLayout>
          </Provider>
        </AntdRegistry>
      </body>
    </html>
  );
}
