"use client";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import React, { useCallback, useEffect } from "react";
import BasicLayout from "@/layouts/BasicLayout";
/*
//国际化
const inter = Inter({ subsets: ["latin"] });

//标题描述
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

//全局初始化逻辑
const InitLayout: React.FC<
  Readonly<{
    children?: React.ReactNode;
  }>
> = ({ children }) => {
  //初始化逻辑
  const doInit = useCallback(() => {
    console.log("init");
  }, []);
//只调用一次
  useEffect(() => {
    doInit();
  }, []);
  return children;
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body>
        <AntdRegistry>
          <InitLayout>
            <BasicLayout>{children}</BasicLayout>
          </InitLayout>
        </AntdRegistry>
      </body>
    </html>
  );
}
